---
- name: Installiere Hauptprogramm (Debian)
  ansible.builtin.apt:
    name: "{{ item.name }}{{ '=' + item.version if item.version|length > 0 else '' }}"
    state: present
  loop: "{{ var_pack_name
    | map('extract', packages.apt)
    | map(attribute='Debian')
    | map(attribute=sys_major|string)
    | flatten }}"
  environment: { DEBIAN_FRONTEND: noninteractive }
  when:
    - ansible_os_family == "Debian"
    - (var_pack_name | default([])) | length > 0
#- name: Installiere Hauptprogramm (RedHat)
#  ansible.builtin.yum:
#    name: "{{ item.name }}{{ '-' + item.version if item.version|length > 0 else '' }}"
#    state: present
#  loop: "{{ var_pack_name
#    | map('extract', packages.yum)
#    | map(attribute='RedHat')
#    | map(attribute=sys_major|string)
#    | flatten }}"
#  when:
#    - ansible_os_family == "RedHat"
#    - (var_pack_name | default([])) | length > 0
#
#- name: Installiere Hauptprogramm (Suse)
#  ansible.builtin.zypper:
#    name: "{{ item.name }}{{ '=' + item.version if item.version|length > 0 else '' }}"
#    state: present
#  loop: "{{ var_pack_name
#    | map('extract', packages.zypper)
#    | map(attribute='Suse')
#    | map(attribute=sys_major|string)
#    | flatten }}"
#  when:
#    - ansible_os_family == "Suse"
#    - (var_pack_name | default([])) | length > 0
#
#- name: Installiere Hauptprogramm (Archlinux)
#  community.general.pacman:
#    name: "{{ item.name }}"
#    state: present
#  loop: "{{ var_pack_name
#    | map('extract', packages.pacman)
#    | map(attribute='Archlinux')
#    | map(attribute=sys_major|string)
#    | flatten }}"
#  when:
#    - ansible_os_family == "Archlinux"
#    - (var_pack_name | default([])) | length > 0
#
#- name: Installiere Hauptprogramm (FreeBSD)
#  community.general.pkgng:
#    name: "{{ item.name }}"
#    state: present
#  loop: "{{ var_pack_name
#    | map('extract', packages.pkgng)
#    | map(attribute='FreeBSD')
#    | map(attribute=sys_major|string)
#    | flatten }}"
#  when:
#    - ansible_os_family == "FreeBSD"
#    - (var_pack_name | default([])) | length > 0
#
